$(document).ready(function(){
	$('.opn-btn').on('click',function(){
		$('#sidebar').fadeIn();
		$('.blurdfg').toggleClass('active');
	});
	$('.return-btn').on('click',function(){
		$('#sidebar').fadeOut();
		$('.blurdfg').toggleClass('active');
	});
	validate({'id':'name','name':'mobile','regex':'[0-9]','length':'10'});
});
