$(document).ready(function(){
	$('.opn-btn').on('click',function(){
		$('#sidebar').fadeIn();
		$('.blurdfg').toggleClass('active');
	});
	$('.return-btn').on('click',function(){
		$('#sidebar').fadeOut();
		$('.blurdfg').toggleClass('active');
	});
});
